[theme]
# Paleta Corpus: blanco (fondo), azul claro (sidebar), azul oscuro (acentos)
base = "light"
primaryColor = "#0A2A6A"            # Azul oscuro (botones, sliders, acentos)
backgroundColor = "#FFFFFF"         # Blanco (lienzo principal)
secondaryBackgroundColor = "#EAF3FF" # Azul claro muy suave (sidebar / paneles)
textColor = "#0B1B34"               # Azul muy oscuro / casi negro (lectura óptima)
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
